### ISSUE TITLE
Run in MacOS

### ISSUE THREAD

**Issue by aditya-08** [Dynamsoft/web-twain-vue-advanced#1]
hello,
trying this in my macbook. when I run it say it please run windows.

![image](https://user-images.githubusercontent.com/44116726/225920661-2ee07ecc-1e31-4b75-8528-4add2febff97.png)

How do I run it in MacOS as well.

**Comment by aditya-08** [comment]
@Ellie-dynamsoft pls can you take a look at this?

**Comment by Ellie-dynamsoft** [comment]
This sample currently supports all platforms, not just Windows only.
